name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        php-version:
          - '8.0'
    env:
      MA_DB_HOST: 127.0.0.1
      MA_DB_NAME: maalps
      MA_DB_USER: root
      MA_DB_PASS: password
      MA_DB_SLAVE: ""
      MA_DB_DSN: mysql:host=localhost;dbname=maalps
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: ${{ env.MA_DB_NAME }}
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
          ini-values: zend.assertions=1

      - name: Start mysql service
        run: sudo /etc/init.d/mysql start

      - name: Verify MySQL connection
        run: |
          mysql --version
          mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "SHOW DATABASES"

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install highest dependencies
        run: composer install --no-interaction --no-progress

      - name: Run setup
        run: composer setup

      - name: Run test suite
        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
